name: Publish to Docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Builder Container
        uses: docker/build-push-action@v1
        with:
          username: pendj
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: pendj/publish-package/game
          tag_with_sha: true
